### ISSUE TITLE
Preserve Hard Privacy

### ISSUE THREAD

**Issue by bmeck** [tc39/proposal-decorators#5]
The current proposal uses a globally exposed prototype to explain PrivateName. This causes some leakage of private state by snooping using:

```js
const old = PrivateName.prototype.set;
PrivateName.prototype.set = (o, v) => {
  log(o, v);
  return old.call(this, o, v);
}
```

This can be used a number of ways (implementing getter/setter functionality, spies, attack, etc.), but I believe invalidates the goals of private state.

This can be somewhat easily changed to not use a shared reference that JS can get to. I am open to any ways to accomplish this, but have an idea below.

1. Change placement to include `"private"`. Privacy is different from `"own"` in that others cannot access it by reflection alone.

2. When creating a descriptor for private fields, change the type to be an AccessorDescriptor bye default, with an internal field to the private field. I think converting it to a DataDescriptor should also be fine while working on it.

```js
descriptor = {
   #field: #foo
   configurable: true,
   get() {},
   set(v) {},
}
```

3. Private field creation does more than mutate existing declarations on the class. I would like to see it be possible, but will not want it breaking hard privacy. If it is needed, for now a WeakMap does work. For now, I would leave mutating the class by adding private fields. The alternative is to return the descriptor on creation like above instead of using the global prototype approach, which I think would seem ok but odd.

**Comment by littledan** [comment]
I'm wondering, how does leaking here differ from WeakMaps leaking everything? You can overwrite the WeakMap methods, and even overwrite the WeakMap constructor itself. Then, when an object puts itself in a WeakMap, *bam*, tell your sidechannel about its value.

About this concrete suggestion:
1. I don't really understand what this has to do with anything. Why not just leave out the key, if it shouldn't be represented, and this could be the signal for private? Also, if you use the placement (rather than a separate attribute), how would you represent which of the three possible places the element comes in?
2. This sounds doable, it just may come with a performance cost for all decorated private fields (or classes with class decorators). More closures may make things slower to run, since they can't always be inlined. cc @bmeurer
3. I'm fine to leave this for later. I just included it because it seems to come up pretty naturally in a bunch of cases, for example, an `@observed` decorator.

**Comment by bmeck** [comment]
I agree that using "placement" is insufficient. Open to whatever makes
sense.

I dont think extra closures are needed; it just avoids having a globally
mutable location where in JS userland they are looked up.

As per WeakMap / WeakSet concerns. They are valid *if* you are not already
copying methods when the collection is constructed or if gloval is already
tainted at time of construction. Be wary if you assume they are
security/privacy feature. I recommend anyone doing so use my method of
copying dynamically looked up and mutable methods/properties to a safe
place.


On Jul 11, 2017 1:07 PM, "Daniel Ehrenberg" <notifications@github.com>
wrote:

I'm wondering, how does leaking here differ from WeakMaps leaking
everything? You can overwrite the WeakMap methods, and even overwrite the
WeakMap constructor itself. Then, when an object puts itself in a WeakMap,
*bam*, tell your sidechannel about its value.

About this concrete suggestion:

   1. I don't really understand what this has to do with anything. Why not
   just leave out the key, if it shouldn't be represented, and this could be
   the signal for private? Also, if you use the placement (rather than a
   separate attribute), how would you represent which of the three possible
   places the element comes in?
   2. This sounds doable, it just may come with a performance cost for all
   decorated private fields (or classes with class decorators). More closures
   may make things slower to run, since they can't always be inlined. cc
   @bmeurer <https://github.com/bmeurer>
   3. I'm fine to leave this for later. I just included it because it seems
   to come up pretty naturally in a bunch of cases, for example, an
   @observed decorator.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/littledan/proposal-unified-class-features/issues/5#issuecomment-314526147>,
or mute the thread

**Comment by littledan** [comment]
> I dont think extra closures are needed; it just avoids having a globally
mutable location where in JS userland they are looked up.

Doesn't turning everything into an accessor create extra closures?

> As per WeakMap / WeakSet concerns. They are valid *if* you are not already
copying methods when the collection is constructed or if gloval is already
tainted at time of construction. Be wary if you assume they are
security/privacy feature. I recommend anyone doing so use my method of
copying dynamically looked up and mutable methods/properties to a safe
place.

I don't understand how copying methods when it's constructed would work. What if they're already monkey-patched when the construction happens? Anyway, for `PrivateName`, you can copy the methods when the decorator executes--this is equivalent to construction time, right?

**Comment by bmeck** [comment]
My though was to use brand checking functions that access internal fields, not have the accessors be bound. This also lets you replace where private storage is placed if redirecting to a different backing store.

My general workflow roughly translates to:

```js
const SECRET = new WeakMap;
for (const key of ["get","has","set"]) SECRET[key] = SECRET[key];
```

Which does not help with tainted globals, but does mean mutation after `SECRET` is allocated does not leak information if globals are untainted. WeakMap cannot be recreated using tamper safe constructs, and we don't have frozen realms or exposed primordials, so there is not much I can do there.

**Comment by littledan** [comment]
@bmeck OK, if we had PrivateNames, couldn't you do something similar, like this?
```
function myDecorator(element) {
  let key = element.key;
  if (typeof key === "privatename") {
    key = Object(key);
    for (const method of ["get", "set"]) key[method] = key[method];
  }
  // Do your decorator stuff here
}
```

**Comment by bmeck** [comment]
Could, but *strongly* feel the need to do so goes against the point of
privacy. Weakmaps are not claiming to be private.

**Comment by littledan** [comment]
I'm confused; I thought privacy was a goal of WeakMaps. cc @erights

Could you say more about the types of "attacks" on privacy that you're concerned about, and what you're able to do to "defend" against them in your environment? In some environments (e.g., SES), you could just freeze `PrivateName.prototype` and `WeakMap.prototype` before any code is run, and it's all done. In other environments, there's a time when you can run some code at the beginning which is assumed to be "pretty early", where methods can be stashed, but it's assumed that "later", polyfills may be run which mess things up (e.g., @ljharb has said that he programs his modules this way). It sounds like you're used to programming with WeakMaps in an environment where there's a bit more of an intermediate trust in things not being changed too early.

What kind of guarantees do you want for private names? Sounds like you want something stronger than what you have for WeakMaps, but I'm not sure exactly what the "threat model" is.

**Comment by bmeck** [comment]
I am aiming to prevent the use of Node internals in ways that cause
compatibility concerns. People already use soft private properties via
underscored property names. My worry is this is a very open hatch that must
be defended every time. Unlike WeakMap etc. which you control the
construction of.

In terms of freezing things early, a better approach is often to subclass
the vulnerable prototype and copy the keys, aimilar to above. This is not
as simple if you do not control what creates you PrivateName.

This does bring up extending PrivateName to something like
SecurePrivateName in my code as long as I can replace the descriptor
safely, but I do t think that is possible without some form of copy
mechanism in the constructor.

**Comment by littledan** [comment]
Actually I think that'd be pretty straightforward to implement, which you could do as follows:

```js
let get = PrivateName.prototype.get;
let set = PrivateName.prototype.set;
class SecurePrivateNameWrapper {
  #pn;
  constructor(pn = PrivateName()) { #pn = pn; }
  get(obj) { return get.call(#pn, obj); }
  set(obj, val) { return set.call(#pn, obj, val); }
  [Symbol.toPrimitive]() { return #pn; }
}
```

Then, whenever you want to call `.get` or `.set` on a PrivateName primitive, you first wrap it in a `SecurePrivateNameWrapper`. 

(Note: I can see here that the logic for decoding the element from a decorator won't permit ToPrimitive to be called the right way here; fixup coming.)

**Comment by littledan** [comment]
Sorry, maybe that doesn't address your concern. What do you mean by "My worry is this is a very open hatch that must be defended every time. Unlike WeakMap etc. which you control the
construction of."? Seems like this is the core of the difference. But aren't you defending the hatch each time by remembering to call out to your WeakMap constructor, rather than the normal one?

**Comment by bmeck** [comment]
@littledan with cases where I create subclasses or manually copy things early I often am doing that to create globals that last the life of a process. Decorators I feel are not always acting like that. 

```js
// top level of a file
const MODULE_MAP = new SecureWeakMap;
```

Is generally how I deal w/ private data currently. I generally have to be careful when allocating things once user code enters the system. With the current [proposed] design, you have a mutable global that generates values that are passed to the decorator functions. That means, upon figuring out if something is a PrivateName (partially complicated by Proxies / Symbol.hasInstance) I have to create something that is a safe wrapper around the potentially unsafe value every time. This is very different than me making some globals that are safe to use for the duration of the process.

I am still unsure *why* there is a desire to make a global prototype at all. Perhaps explaining why there should be one might help me understand why privacy is not a concern with PrivateName (or perhaps it should be renamed to drop Private bit)

**Comment by littledan** [comment]
Well, we could remove PrivateName from the global object, requiring a couple lines of code to get at it. I don't care which way we go there. But there are a couple examples to making it a class-like thing instead of detached getter-setter pairs:
- It could be hard for implementations to eliminate the closures, leading to performance overhead (vs methods that are shared with everything)
- It gives a clear API for making synthetic private fields, which is analogous to how public fields and user private fields work

Anyway, I'm fine to iterate here, that's just the rationale for the current design (plus that I don't have it fully formed in my head how it'd look otherwise).

**Comment by littledan** [comment]
@bmeck and I discussed this issue a bit further offline. It sounds like we could address the issue with just a minor tweak to the API. Rather than expose the functions `PrivateName.prototype.get` and `PrivateName.prototype.set` as ordinary properties on the prototype, the functions should be exposed in some way that can't be tampered with.

Strawman API:
- Decorators for private fields and methods have extra properties in the descriptor which point to the get and set functions.
- `PrivateName()` returns, rather than a Private Name primitive, an object which has three properties, for the name, the get function, and the set function.

I'm not sure if this is absolutely necessary for Node Core, if Node Core might be able to pull off these two functions during bootstrapping, but it may help others who are not able to run code "at the beginning" to get the original copy of the methods.

Any thoughts?

**Comment by bmeck** [comment]
I am not tied to any given API but a large +1

**Comment by erights** [comment]
I understand the first bullet (extra properties in the "descriptor" given to the decorator).

I do not understand the second bullet. Why would we need `PrivateName()` ? Why isn't the first bullet sufficient?

**Comment by littledan** [comment]
Because when you construct a new private name, you might not have the get and set functions to work with. Any decorator may want to create a private name, not just decorators for private fields.

However, maybe we should just give the three functions, PrivateName, get and set, to all decorators.

**Comment by erights** [comment]
What are the signatures of the three functions?

What happens if the PrivateName function is called after the class is initialized?

**Comment by littledan** [comment]
Same signatures as the functions in the draft specification, and same behaviour. It's the same function identity as well, not different each time. The functions would not expire or anything.
