### ISSUE TITLE
Context.private doesn't seem to support group accessor

### ISSUE THREAD

**Issue by bigopon** [tc39/proposal-decorators#510]
I originally created an issue to ask the question here https://github.com/tc39/proposal-grouped-and-auto-accessors/issues/13

Though after some time, I think maybe I should ask here too. At the moment, context.private as a boolean is fine because it's only a single element being decorated. How will this work later in case there's more than 1 element decorated like examples the grouped accessor proposal?

```ts
class A {
  @deco
  accessor id { get; #set }
}

function deco({}, context) {
  context.private // what's the value of this?
}
```

**Comment by pzuraq** [comment]
I think this is out of scope for this proposal, since grouping is still in the early stages and could change significantly. The ability to have a split public/private getter/setter in particular has been contentious I believe, since it would mean implicitly introducing a private identifier that doesn't actually exist in the code itself. 

I think if that design does move forward, there are a number of ways we could support this. We may be able to add a different type to `private` (e.g. allow it to be an object with `get`/`set` properties) or we may use a different `kind` for the context object and a different shape altogether.

I'm going to close this issue here, discussion should continue in the Grouped and Auto Accessor proposal repo.
